// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';
import {context} from '../models';

export function Connect():Promise<void>;

export function Disconnect():Promise<void>;

export function GetAbout():Promise<wails.AboutInfo>;

export function GetCapabilities():Promise<Array<wails.CapabilityInfo>>;

export function GetConfig():Promise<wails.Config>;

export function GetDeviceInfo():Promise<wails.DeviceInfo>;

export function GetLogs(arg1:wails.LogFilter):Promise<Array<wails.LogEntry>>;

export function GetRecentActivity():Promise<Array<wails.ActivityEntry>>;

export function GetStatus():Promise<wails.ConnectionStatus>;

export function InvokeCommand(arg1:string,arg2:{[key: string]: any}):Promise<wails.InvokeResult>;

export function OpenPath(arg1:string):Promise<void>;

export function SaveConfig(arg1:wails.Config):Promise<void>;

export function SaveFileToDisk(arg1:string,arg2:string):Promise<void>;

export function SetCapability(arg1:string,arg2:boolean):Promise<void>;

export function TestConnection():Promise<wails.TestResult>;

export function WailsInit(arg1:context.Context):Promise<void>;
