// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['wails']['App']['Connect']();
}

export function Disconnect() {
  return window['go']['wails']['App']['Disconnect']();
}

export function GetAbout() {
  return window['go']['wails']['App']['GetAbout']();
}

export function GetCapabilities() {
  return window['go']['wails']['App']['GetCapabilities']();
}

export function GetConfig() {
  return window['go']['wails']['App']['GetConfig']();
}

export function GetDeviceInfo() {
  return window['go']['wails']['App']['GetDeviceInfo']();
}

export function GetLogs(arg1) {
  return window['go']['wails']['App']['GetLogs'](arg1);
}

export function GetRecentActivity() {
  return window['go']['wails']['App']['GetRecentActivity']();
}

export function GetStatus() {
  return window['go']['wails']['App']['GetStatus']();
}

export function InvokeCommand(arg1, arg2) {
  return window['go']['wails']['App']['InvokeCommand'](arg1, arg2);
}

export function OpenPath(arg1) {
  return window['go']['wails']['App']['OpenPath'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['wails']['App']['SaveConfig'](arg1);
}

export function SaveFileToDisk(arg1, arg2) {
  return window['go']['wails']['App']['SaveFileToDisk'](arg1, arg2);
}

export function SetCapability(arg1, arg2) {
  return window['go']['wails']['App']['SetCapability'](arg1, arg2);
}

export function TestConnection() {
  return window['go']['wails']['App']['TestConnection']();
}

export function WailsInit(arg1) {
  return window['go']['wails']['App']['WailsInit'](arg1);
}
